<a href="https://colab.research.google.com/github/svrajeshkumar/tensorflow_certification/blob/main/00Lesson_Tensor_Flow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this Notebook, i will be learning fundemental concepts of tensors using tensorflow

Following topics will be covered

* Introduction to tensors
* Gettings information from tensors
* Manipulating Tensors
* Tensors * Numpy
* Using @tf.function (way to speed up python functions)
* Using GPU and TPU
* Excersizes

# Introduction to Tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
#create tensors using tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the no.of dimensions of a tensor (ndim)
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check dimension of vector
vector.ndim

1

In [ ]:
#create a metrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix
an_matrix = tf.constant([[10.,2],
                        [2.,6],
                         [14.,6]], dtype=tf.float16) #specify with dtype parameter
an_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  2.],
       [ 2.,  6.],
       [14.,  6.]], dtype=float16)>

In [ ]:
#ndim of another matrix
an_matrix.ndim

2

In [ ]:
#crate a tensor with more dimensions
m_matrix = tf.constant([[[1,2,3],
                         [2,3,5]],
                         [[6,7,8],
                         [8,9,0]],
                         [[11,12,14],
                          [21,11,22]]
                         ])
m_matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  3,  5]],

       [[ 6,  7,  8],
        [ 8,  9,  0]],

       [[11, 12, 14],
        [21, 11, 22]]], dtype=int32)>

In [ ]:
m_matrix.ndim

3

#what we created so far :
* scalar a single number
* vector a number with director
* Matrix a 2 dimensional array of numbers
* Tensor an n Dimensional array of numbers (0 dimensional is scalar, 1 dimensional is vector)

### Creating Tensors with tf.variable

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [23]:
c_var = tf.Variable([10,7])
unchangeable_ten = tf.constant([19,7])
c_var , unchangeable_ten

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([19,  7], dtype=int32)>)