<a href="https://colab.research.google.com/github/svrajeshkumar/tensorflow_certification/blob/main/00Lesson_Tensor_Flow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this Notebook, i will be learning fundemental concepts of tensors using tensorflow

Following topics will be covered

* Introduction to tensors
* Gettings information from tensors
* Manipulating Tensors
* Tensors * Numpy
* Using @tf.function (way to speed up python functions)
* Using GPU and TPU
* Excersizes

# Introduction to Tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
#create tensors using tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#check the no.of dimensions of a tensor (ndim)
scalar.ndim

0

In [7]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
#check dimension of vector
vector.ndim

1

In [11]:
#create a metrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [12]:
matrix.ndim

2