<a href="https://colab.research.google.com/github/svrajeshkumar/tensorflow_certification/blob/main/00Lesson_Tensor_Flow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this Notebook, i will be learning fundemental concepts of tensors using tensorflow

Following topics will be covered

* Introduction to tensors
* Gettings information from tensors
* Manipulating Tensors
* Tensors * Numpy
* Using @tf.function (way to speed up python functions)
* Using GPU and TPU
* Excersizes

# Introduction to Tensors

In [87]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [88]:
#create tensors using tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [89]:
#check the no.of dimensions of a tensor (ndim)
scalar.ndim

0

In [90]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [91]:
#check dimension of vector
vector.ndim

1

In [92]:
#create a metrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [93]:
matrix.ndim

2

In [94]:
#create another matrix
an_matrix = tf.constant([[10.,2],
                        [2.,6],
                         [14.,6]], dtype=tf.float16) #specify with dtype parameter
an_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  2.],
       [ 2.,  6.],
       [14.,  6.]], dtype=float16)>

In [95]:
#ndim of another matrix
an_matrix.ndim

2

In [96]:
#crate a tensor with more dimensions
m_matrix = tf.constant([[[1,2,3],
                         [2,3,5]],
                         [[6,7,8],
                         [8,9,0]],
                         [[11,12,14],
                          [21,11,22]]
                         ])
m_matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  3,  5]],

       [[ 6,  7,  8],
        [ 8,  9,  0]],

       [[11, 12, 14],
        [21, 11, 22]]], dtype=int32)>

In [97]:
m_matrix.ndim

3

#what we created so far :
* scalar a single number
* vector a number with director
* Matrix a 2 dimensional array of numbers
* Tensor an n Dimensional array of numbers (0 dimensional is scalar, 1 dimensional is vector)

### Creating Tensors with tf.variable

In [98]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [99]:
c_var = tf.Variable([10,7])
unchangeable_ten = tf.constant([19,7])
c_var , unchangeable_ten

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([19,  7], dtype=int32)>)

In [100]:
#change one element in changeable tensor
c_var[0] = 7
c_var

TypeError: ignored

In [102]:
#how about we try .assign()
c_var[0].assign(7)
c_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [103]:
#try change our unchangeable tensor
unchangeable_ten[0].assign(9)
unchangeable_ten

AttributeError: ignored

###creating random tensors


#Random tensors are tensors some abitrary size

In [104]:
#create a 2 random tensors

r_1 = tf.random.Generator.from_seed(42)
r_1 = r_1.normal(shape=(3,2))
r_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [105]:
r_2 = tf.random.Generator.from_seed(12)
r_2 = r_2.normal(shape=(2,2))
r_2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.0130816 ,  0.28291714],
       [ 1.2132233 ,  0.46988967]], dtype=float32)>

In [106]:
r_1,r_2, r_1 == r_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=bool, numpy=False>)


###Shuffling the order of elements of Tensors

In [107]:
#Shuffle a Tensor  (Useful when your want to shuffle your data)

n_shuffle = tf.constant([[10,7],
                         [3,6],
                         [2,5]])
n_shuffle
tf.random.set_seed(42)
tf.random.shuffle(n_shuffle,seed=42) #operational level random seed




<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  6],
       [ 2,  5]], dtype=int32)>

###Otherways to make tensors

In [108]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [109]:
#Create a tensor of all Zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

# Turn Numpy arrays in Tensors
### Main Difference is that Tensors can eb run on GPU much faster

In [110]:
import numpy as np
num_A = np.arange(1,25, dtype=np.int32)
num_A
# X = tf.constant(some_matrix)
# y = tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [111]:
AB = tf.constant(num_A, shape=(3,8))
AB


<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [112]:
2 * 3 * 4
3 * 8

24

### Getting information from tensors

When dealing with tensors, following attributes are imp
 * Shape
 * Rank
 * Axis or dimension
 * Size

In [115]:
#Create a Rank 4 Tensor (4 Dimensions)

rank_4_t = tf.zeros(shape=[2,3,4,5])
rank_4_t

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>